### ISSUE TITLE
Unable to set instanceName

### ISSUE THREAD

**Issue by mariwing** [mKeRix/ansible-playbooks#11]
Hi, I have ansible running. Thanks for teaching me about that tool, seems great :-)

I am facing a issue; I want to set the instanceName. As soon as I include that in the config the playbook just hangs. This is the config that causes the hang:

```yml
all:
  hosts:
    'plantgw.ONONETT':
      room_assistant_config:
        global:
          instanceName: 'stue'
    'black-pearl.ONONETT':
      room_assistant_config:
        global:
          instanceName: 'soverom'
```

Just using this works great:
```yml
all:
  hosts:
    'plantgw.ONONETT':
    'black-pearl.ONONETT':
```

Any tips or hints on how to achieve what I want?
