### ISSUE TITLE
No config file created

### ISSUE THREAD

**Issue by robeving** [mKeRix/ansible-playbooks#12]
I am an ansible noob. I've followed the instructions on the room assistant docs page, I can see node and other dependencies are installed. Room assistant is running BUT there is no config in ~/room-assistant.

I'm running ansible on a Pi3 with Python 3.8. My Ansible version is 2.10.3 and its running under a venv environment.

In the ansible log these lines are emitted - no errors are seen. 

```
TASK [room-assistant : Create global config file] *****************************************************************************************************
skipping: [172.16.2.250]
skipping: [172.16.2.161]
skipping: [172.16.2.3]

TASK [room-assistant : Create config file] ************************************************************************************************************
skipping: [172.16.2.250]
skipping: [172.16.2.161]
skipping: [172.16.2.3]
```

I couldn't get the command line in the docs to work. I'm running this command:
`ansible-playbook room-assistant.yml -e hosts.yaml -i hosts -k`

Where hosts is a ansible INI style file that just defines my hosts. I think this might be the problem but I get failures using the samples supplied in this repo and in the room assistant docs (hosts can be found in inventory).

Here is my hosts.yaml file:

```
all:
  hosts:
    172.16.2.3:
      room_assistant_config:
        global:
          cluster:
            networkInterface: eth0.200
            instanceName: office
        bluetoothClassic:
          minRssi: -6
    172.16.2.250:
      room_assistant_config:
        global:
          instanceName: livingroom
    172.16.2.161:
      room_assistant_config:
        global:
          instanceName: kitchen
  vars:
    room_assistant_version: latest
    room_assistant_global_config:
      global:
        integrations:
          - homeAssistant
          - bluetoothClassic
      homeAssistant:
        mqttUrl: mqtt://172.16.2.3:1883
      bluetoothClassic:
        addresses:
        - 'XX:XX:XX:XX:XX:XX' # a
        - 'XX:XX:XX:XX:XX:XX # b
```

Any ideas what is wrong? I would like to use this but i'm on the verge of rage quitting.
