### ISSUE TITLE
local.yml not populating with all settings from host.yml file

### ISSUE THREAD

**Issue by townsmcp** [mKeRix/ansible-playbooks#19]
@mKeRix would you mind having a look over this issue please.
So I can install RA on 2 seperate pi's but thought I would give Ansible a try. To be clear, I got both pi's working manually (an RPI zero 2w and 4b). I have created the host file however when I run the command to update the host.yml files, only part of the local.yml file is populating.
So my host.yml code is:
```
all:
  hosts:
    '192.168.1.149':
      ansible_user: pi
      ansible_password: XXX
      room_assistant_config: 
        cluster:
          autoDiscovery: true
          port: 6425
          weight: 100
          quorum: 2
          peerAddresses:
            - 192.168.1.231:6425
        global:
          instanceName: DiningRoomRA
    '192.168.1.231':
      ansible_user: pi
      ansible_password: XXX
      room_assistant_config: 
        cluster:
          autoDiscovery: true
          port: 6425
          weight: 100
          quorum: 2
          peerAddresses:
            - 192.168.1.149:6425
        global:
          instanceName: mbRA
  vars:
    room_assistant_version: 3.0.0-beta.4
    room_assistant_global_config:
      global:
        integrations:
          - homeAssistant
          - bluetoothClassic
          - bluetoothLowEnergy
      homeAssistant:
        mqttUrl: 'mqtt://192.168.1.198:1883'
        mqttOptions:
          username: mqtt-user
          password: XXX
      bluetoothClassic:
        minRssi: -20
        hciDeviceId: 0
        addresses:
          - 'E8:81:52:3D:B9:XX' # James Apple Watch
#          - '8C:EC:7B:57:52:XX' # James iPhone
#          - '18:F1:D8:E4:1E:XX' # Dylan iPhone
          - 'C0:A5:3E:9C:B3:XX' # Dylan Apple Watch
#          - 'F8:2D:7C:A0:62:XX'  # Tiffany iPhone
          - 'F8:6F:C1:52:6B:XX'  # Tiffany Apple Watch
#          - '8C:EC:7B:54:E3:XX' # Cheryl iPhone
          - 'E8:81:52:BD:2F:XX' # Cheryl Apple Watch
      bluetoothLowEnergy:
        #  minDiscoveryLogRssi: -80
        timeout: 60
        #  instanceBeaconEnabled: false
        minDiscoveryLogRssi: -30
        allowlist:
        - '0CAAEC32-E84C-4750-9817-XXXXXXXXX' # James iPhone
        - 'BE0B4F11-5FE2-4518-A66A-XXXXXXXXX' # Tiffany iPhone
        - '96E86366-BBED-430B-BA87-XXXXXXXXX' # Dylan iPhone
        - '5C83EFAB-4F8C-4E10-8746-XXXXXXXXX' # Cheryl iPhone
        tagOverrides:
          0CAAEC32-E84C-4750-9817-XXXXXXXXX:
            name: James iPhone BLE
          BE0B4F11-5FE2-4518-A66A-XXXXXXXXX:
            name: Tiffany iPhone BLE
          96E86366-BBED-430B-BA87-XXXXXXXXX:
            name: Dylan iPhone BLE
          5C83EFAB-4F8C-4E10-8746-XXXXXXXXX:
            name: Cheryl iPhone BLE
```

After running the ansible update to push the config to the pi's the DiningroomRA local.yml file only contains:
```
cluster:
  autoDiscovery: true
  peerAddresses:
  - 192.168.1.231:6425
  port: 6425
  quorum: 2
  weight: 100
global:
  instanceName: DiningRoomRA
```

After running the ansible update to push the config to the pi's the mbRA local.yml file only contains:
```
cluster:
  autoDiscovery: true
  peerAddresses:
  - 192.168.1.149:6425
  port: 6425
  quorum: 2
  weight: 100
global:
  instanceName: mbRA
```

I can manually edit the pi local.yml files however I would love to get this working via ansible so I can make the change in one place and push to all.
Thanks in advance
