### ISSUE TITLE
Hangs at 'Gathering Tasks'

### ISSUE THREAD

**Issue by rrosson** [mKeRix/ansible-playbooks#2]
When following your instructions for using ansible to deploy room-assistant to my 'pi zero w' devices it hangs at "Gathering Facts". The command line I am using is:
```
ansible-playbook -i hosts.yml -u pi -k room-assistant.yml 
```
Contents of my hosts.yml (passwords and IP's have been changed) file is:
```
all:
        hosts:
                192.168.xx.xxx  # Office
  vars:
    room_assistant_global_config:
      global:
        integrations:
          - homeAssistant
          - bluetoothClassic
      homeAssistant:
        mqttUrl: mqtt://hassio.local:1883
        mqttOptions:
          username: room-assistant
          password: secretpass
      bluetoothClassic:
        addresses:
          - 'xx:xx:xx:xx:xx:xx'
```
and the contents of my room-assistant.yml is:
```---
- hosts: all
  roles:
    - nodejs
    - room-assistant
```
ansible version (running on ubuntu 18.x) is:
```
ansible 2.9.6
python version = 2.7.17 (default, Nov  7 2019, 10:07:09) [GCC 7.4.0]
```

**Comment by mKeRix** [comment]
I think your hosts.yml may be a bit malformed, try:

```yaml
all:
  hosts:
    '192.168.xx.xxx':  # Office
  vars:
    room_assistant_global_config:
      global:
        integrations:
          - homeAssistant
          - bluetoothClassic
      homeAssistant:
        mqttUrl: mqtt://hassio.local:1883
        mqttOptions:
          username: room-assistant
          password: secretpass
      bluetoothClassic:
        addresses:
          - 'xx:xx:xx:xx:xx:xx'
```
